# Generated by Django 4.1.3 on 2022-11-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=8)),
                ('curso', models.IntegerField()),
                ('creditos', models.IntegerField()),
                ('pre_requisitos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='materia.materias')),
            ],
        ),
    ]
