# Generated by Django 4.1.3 on 2022-11-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_remove_materias_pre_requisitos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='creditos',
            field=models.IntegerField(default=3),
        ),
    ]
