# Generated by Django 4.1.3 on 2022-11-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0003_alter_materias_creditos'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='tipo',
            field=models.CharField(default='N', max_length=8),
        ),
    ]
