# Generated by Django 4.1.3 on 2022-11-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0004_materias_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='tipo',
            field=models.CharField(choices=[('N', 'normal'), ('O', 'optativa')], default='N', max_length=8),
        ),
    ]
