# Generated by Django 4.1.3 on 2022-12-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0005_alter_materias_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='tiene_lab',
            field=models.BooleanField(default=False),
        ),
    ]
