# Generated by Django 4.1.3 on 2022-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_horaria', models.IntegerField()),
                ('aula', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('lab', 'Laboratorio'), ('teo', 'Teoria')], default='teo', max_length=3)),
            ],
        ),
    ]
