# Generated by Django 4.1.3 on 2022-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_rename_decente_horarios_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='grupo',
            field=models.IntegerField(default=11),
        ),
    ]
