# Generated by Django 4.1.3 on 2023-01-02 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0004_horarios_grupo'),
        ('alumnos', '0003_alumnos_cu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('gestion', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumnos')),
                ('horarios', models.ManyToManyField(to='horarios.horarios')),
            ],
        ),
    ]
