# Generated by Django 4.1.3 on 2022-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_last_name_alter_usuarios_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
