# Generated by Django 3.2.2 on 2022-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
