# Generated by Django 3.2.2 on 2022-12-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20221130_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
