# Generated by Django 4.1.3 on 2022-11-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kardex', '0007_remove_kadex_anio_remove_kadex_estado_and_more'),
        ('materia', '0005_alter_materias_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('anio', models.IntegerField(blank=True, null=True)),
                ('gestion', models.IntegerField(choices=[(1, 'primero'), (2, 'Reprobado')], default=1)),
                ('final', models.IntegerField()),
                ('segunda_instancia', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ap', 'Aprobado'), ('rp', 'Reprobado'), ('co', 'Convalidado')], default='ap', max_length=2)),
                ('materia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='materia.materias')),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.kadex')),
            ],
        ),
    ]
