# Generated by Django 4.1.3 on 2022-12-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_alter_calificaciones_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='estado',
            field=models.CharField(choices=[('apro', 'Aprobado'), ('rp', 'Reprobado'), ('co', 'Convalidado')], default='apro', max_length=15),
        ),
    ]
