# Generated by Django 4.1.3 on 2022-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_alter_calificaciones_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='estado',
            field=models.CharField(choices=[('ap', 'Aprobado'), ('rp', 'Reprobado'), ('co', 'Convalidado')], default='ap', max_length=15),
        ),
    ]
