# Generated by Django 4.1.3 on 2022-12-22 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0006_materias_tiene_lab'),
        ('calificaciones', '0004_alter_calificaciones_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materia.materias'),
        ),
    ]
