# Generated by Django 4.1.3 on 2022-12-22 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0006_materias_tiene_lab'),
        ('calificaciones', '0005_calificaciones_id_alter_calificaciones_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.materias'),
        ),
    ]
