# Generated by Django 4.1.3 on 2022-12-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0006_alter_calificaciones_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='anio',
            field=models.IntegerField(blank=True, default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
