# Generated by Django 4.1.3 on 2023-01-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0007_alter_calificaciones_anio_alter_calificaciones_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='gestion',
            field=models.IntegerField(choices=[(1, 'primero'), (2, 'segundo')], default=1),
        ),
    ]
