# Generated by Django 4.1.3 on 2022-11-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadex',
            name='gestion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kadex',
            name='plan',
            field=models.IntegerField(default=1),
        ),
    ]
