# Generated by Django 4.1.3 on 2022-11-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_alter_kadex_gestion_alter_kadex_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadex',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kadex',
            name='gestion',
            field=models.IntegerField(choices=[(1, 'primero'), (2, 'Reprobado')], default=1),
        ),
    ]
