# Generated by Django 4.1.3 on 2022-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0005_alter_materias_tipo'),
        ('kardex', '0003_kadex_anio_alter_kadex_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadex',
            name='materias',
            field=models.ManyToManyField(to='materia.materias'),
        ),
    ]
