# Generated by Django 4.1.3 on 2022-11-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0004_kadex_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kadex',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='kadex',
            name='nombre_materia',
        ),
        migrations.RemoveField(
            model_name='kadex',
            name='sigla',
        ),
    ]
