# Generated by Django 4.1.3 on 2022-11-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0005_remove_kadex_curso_remove_kadex_nombre_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadex',
            name='segunda_instancia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
